# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ede836021d8dff3bb65d5142c9902dda9c7bc25393cc6a85321f8344a83f6ddd73c409f6e46e6ef79b4e2df836fe1f69bf69c02d2675687ccf6c06bd8b0f11e

test:
  secret_key_base: d6e84d3f74ca3be4ee0aceebe8457309ccf550d7d2612346e31a35c49ecce9c83aefbf2c9d0ab90c592f867e7fde25d30ce43794357662862da08475067d3fc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
